### PR TITLE
Add FAQ about spent coin status

### PR DESCRIPTION
**Pull request by RiccardoMasutti**

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
And for the record, this is a fork of @nopara73 FAQ repo https://github.com/nopara73/NoparaFaq, I think it's better to have this explanation in the docs, so to have it all in one place.

**Comment by yahiheb** [comment]
@MaxHillebrand I think @nopara73 wanted to use the text editor to change that on purpose.

And by changing that the next sentence `Wasabi will think that the wallet was loaded in...` becomes wrong (or unnecessary)

**Comment by MaxHillebrand** [comment]
@nopara73 is there any reason why the manual config file change? In my experience it is fixed with the GUI way too...

**Comment by nopara73** [comment]
> @nopara73 is there any reason why the manual config file change? In my experience it is fixed with the GUI way too...

There is none.

**Comment by yahiheb** [comment]
One thing to note though, nopara suggested to edit the `yourwalletname.json` file but using the GUI the `Config.json` file will be the one edited, is there any difference?

**Pull request merged**
