### PR TITLE
Add shields image

### PR DESCRIPTION
**Pull request by dennisreimann**
As requested in #478.

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
@MaxHillebrand that would be awesome!

**Comment by yahiheb** [comment]
> But @dennisreimann, I thought rather about having a shield as icon within the line of test, so that we can replace the words red shield yellow shield green shield check-mark shield with icons directly in the line. I'm not sure if I explain it properly...

I say we merge this and do what Max suggested in another PR

**Comment by MaxHillebrand** [comment]
@yahiheb, he's working on this right now, I'll merge the proper version directly in just one moment. 

image

**Comment by dennisreimann** [comment]
Updated as discussed with @MaxHillebrand. 🛡

**Pull request merged**
