### PR TITLE
[STRUCTURE] Add Description to each file

### LINKED ISSUE #137: Link preview text
### Problem

Right now the link preview text shows always the same, regardless what link is used. This is unspecific and does not give an accurate preview of what the linked content actually is.

screenshot_20190810_113125

### Solution

Is it possible to give a more precise preview, either for the specific markdown file [in this case a summary of the BIP.md file] or even better, for the specific header within the markdown file [in this case a summary of BIP158].

### PR DESCRIPTION
**Pull request by MaxHillebrand**
This PR closes #137 and closes #127.

Every markdown file in the doc has added the frontmatter json to enable link highlights of that given file. The sentence `This is the Wasabi documentation, an archive of knowledge about the open-source, non-custodial and privacy-focused Bitcoin wallet for desktop.` is added to all files so that the preview is clearly linked to the docs.

```
---
{
  "title": "foo",
  "description": "bar"
}
---
```

### CODE REVIEW

**Comment by dennisreimann** [comment]
Awesome, thanks for all the effort, Max!

**Comment by yahiheb** [comment]
@MaxHillebrand Will this title and description be displayed anywhere?

**Comment by MaxHillebrand** [comment]
As far as I understand it, this is shown for link previews [see picture #137], and I'm not sure if it is shown anywhere else...

**Comment by yahiheb** [comment]
My point is if we don't display the title and the description anywhere what is the point of writing them? specially the repeated sentence.

**Comment by MaxHillebrand** [comment]
My main reason is the link preview. I reference this doc many times already with the link. And so far it only says the one sentence, regardless what file I share. But now, it actually shows at least the rough topic about it, and also that it is the Wasabi docs.

If you want to change the tagline of the GUI website home page, then check the [`docs/README.md`](https://github.com/zkSNACKs/WasabiDoc/blob/master/docs/README.md).

**Pull request merged**
