### PR TITLE
Edit the main README file

### PR DESCRIPTION
**Pull request by yahiheb**
Correct some typos, remove some redundant sentences, put new sentence in a new line and fix some links.

### CODE REVIEW

**Comment by yahiheb** [comment]
@MaxHillebrand Shouldn't we say `Wasabi Wallet's` instead of Wasabi Wallets?
`If you have a question ...` this sentence is redundant.

**Comment by MaxHillebrand** [comment]
but is this not an abbreviation of `Wasabi Wallet is`?

**Comment by yahiheb** [comment]
This is `possessive 's`.

**Comment by MaxHillebrand** [comment]
ok, you're right, I fixed it here https://github.com/zkSNACKs/WasabiDoc/commit/86bab5de256a8415af2dac28d012a9390f96538e

**Pull request merged**
