### PR TITLE
[FAQ] legal documents

### PR DESCRIPTION
**Pull request by MaxHillebrand**
This ready for review branch adds links to the legal documents in the FAQ, and adds the summary as standalone question. As discussed in #713, we should not have the whole legal documents in the docs, but I think the summary points are good to have.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
The only other place where the TaC are mentioned is [here in the step by step wallet creation](https://docs.wasabiwallet.io/using-wasabi/WalletGeneration.html#generating-the-wallet-step-by-step), and I am not sure if we should link to the main repo, as it might clutter and distract the reader of the initial guide...

**Comment by yahiheb** [comment]
Let's wait for @bharmat's or @hgergoil's comments to see if it is fine to add a summary of the legal documents.

**Comment by hgergoil** [comment]
> The only other place where the TaC are mentioned is [here in the step by step wallet creation](https://docs.wasabiwallet.io/using-wasabi/WalletGeneration.html#generating-the-wallet-step-by-step), and I am not sure if we should link to the main repo, as it might clutter and distract the reader of the initial guide...

I agree with RiccardoMasutti, we shouldn't add any links to the documentation...

**Comment by RiccardoMasutti** [comment]
@MaxHillebrand ?

**Comment by yahiheb** [comment]
@MaxHillebrand Why was this merged?

**Pull request merged**
