### PR TITLE
[WIP] Add 1.1.12 contribution game

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Following https://github.com/zkSNACKs/WalletWasabi/issues/3783

### CODE REVIEW

**Comment by lontivero** [comment]
This makes no sense to me. Why are we communicating about contribution games, rewards (money) and those kinds of thing in the Wasabi documentation?

**Comment by yahiheb** [comment]
@RiccardoMasutti 
> After three more months of work since the previous major release of v1.1.11

It has been only 2 months since that release.

> and the contribution game had a total bounty of `0.3 bitcoin`, sponsored by zkSNACKs.

Where did you get that information from?

**Comment by RiccardoMasutti** [comment]
@yahiheb I copied it from the last game.

**Comment by yahiheb** [comment]
Come on seriously?

**Comment by MaxHillebrand** [comment]
I don't know if there will be such a contribution game again for the release...

Please first discuss this in slack with us first, before opening the issue copying last time.

**Pull request closed without merging**
