### PR TITLE
Change from $1000 to 0.1 BTC

### PR DESCRIPTION
**Pull request by RiccardoMasutti**

### CODE REVIEW

**Comment by yahiheb** [comment]
NACK. the bounty is 1000 $ not 0.1 btc.

**Comment by RiccardoMasutti** [comment]
@MaxHillebrand ?

**Comment by yahiheb** [comment]
Here it is 10 million sats (0.1 btc) https://twitter.com/HillebrandMax/status/1158379137511374848
But here it is 1000$ worth of bitcoin https://docs.wasabiwallet.io/building-wasabi/ContributionGame.html#monthly-contribution-game-for-the-documentation

We can make it like this: 0.1 btc when the bitcoin price is high OR 1000$ when the price is low. haha

Jokes aside I think Max means 1000$ worth of bitcoin in his tweet .

**Comment by RiccardoMasutti** [comment]
Closing as bounty is $1000/month

**Comment by MaxHillebrand** [comment]
Yes, zkSNACKs expenses are denominated in USD, though always paid out in bitcoin. It just happened to be pretty much exactly 0.1 for the first couple months.

**Pull request closed without merging**
