### PR TITLE
Improve RPC documentation for Windows

### LINKED ISSUE #1608: Create RPC Documentation for Windows
It doesn't work. A person with Windows must go through it and document the necessary steps for Windows.

Related:
- curl setup
- jq setup
- escaping json characters https://github.com/zkSNACKs/WalletWasabi/issues/11678

### PR DESCRIPTION
**Pull request by yahiheb**
Closes #1608

### CODE REVIEW

**Review by MaxHillebrand — COMMENTED** [review]
Maybe add an example?
I don't understand exactly what this means

**Review by nopara73 — CHANGES_REQUESTED** [review]
Bare minimal. I like your thinking.

- [ ] Have you try your suggestions?
- [ ] `curl` is also not default on Windows I think
- [ ] example (what Max said)
- [ ] I haven't tried git bash, have you? Does it really come with `curl` and `jq`? Just confirming.

**Comment by yahiheb** [comment]
> Have you try your suggestions?

Yes ofc.

> `curl` is also not default on Windows I think

Windows 10, version 1803 or later.

> example (what Max said)

Done.

> I haven't tried git bash, have you? Does it really come with `curl` and `jq`? Just confirming.

Yes I always use Bash, it is good.
No it doesn't come with those but if you use Bash you don't need to use double quotation marks or to escape them, you just use the methods as they are now in the docs. IMO this is the best option.

**Review by nopara73 — APPROVED** [review]
LGTM utACK

**Pull request merged**
