### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by BTCparadigm**
Created 2 tables of content. Added a picture, some emojis and a link to Discussions, instead of Issues in WalletWasabi repo.

https://github.com/BTCparadigm/WasabiDoc/blob/BTCparadigm-patch-2/README.md

### CODE REVIEW

**Comment by BTCparadigm** [comment]
Not sure if I made this correctly by creating patches like this. This patch (2) includes the changes of [patch-1](https://github.com/zkSNACKs/WasabiDoc/pull/982)

**Comment by BTCparadigm** [comment]
Apparently I created what is known as "merge hell". 
Thanks @MaxHillebrand helping me solve it and for the tips to avoid it in the future.

r_674227_nSiDU

**Comment by yahiheb** [comment]
IMO it would be better to split this PR into two PRs, one to update the README file and another for the other edits, in order to make it easy to review the changes.

**Comment by BTCparadigm** [comment]
Separated README.md changes from [other changes](#982), which were combined in this #983.

New PR #984

**Pull request closed without merging**
