### PR TITLE
Open FAQ dropdown when searched

### LINKED ISSUE #451: Open FAQ dropdown when searched
In the old search engine, if I clicked on a FAQ search result, then it jumped to that header in the file and also opened the dropdown.

With the Algolia search engine, it does only jump to the ### header, but it does not open the dropdown, which makes it a bit cumbersome to search the FAQ, as the result is not immediately clear.

Can Algolia also open the dropdown?

### PR DESCRIPTION
**Pull request by dennisreimann**
Fixes #451.

### CODE REVIEW

**Comment by yahiheb** [comment]
This didn't work for me.

**Comment by dennisreimann** [comment]
@yahiheb What in particular does not work for you? There are differnet cases in which the FAQ opening should work:

- Initial page load (coming to the page with an `#`-anchor for an FAQ item
- Switching the page and opening a particular FAQ (most likely the search case)
- Opening an FAQ item on the same page

Have you tried cleaning the browser cache to make sure you are using this version of the JavaScript?

**Comment by yahiheb** [comment]
I tried using another browser, it is working (it collapses the FAQ when using search), but in some cases it doesn't:

- Go to http://localhost:8080/
- Search for `who can use wasabi`
- Click the result

The FAQ has not been collapsed.
If you search again it will work properly.

**Comment by dennisreimann** [comment]
Ok, based on your feedback I got an idea what might be wrong. I'll update this :)

**Comment by yahiheb** [comment]
> and the url in the browser links to lurking wife mode.

The lurking wife link problem was fixed here https://github.com/zkSNACKs/WasabiDoc/pull/472

**Comment by dennisreimann** [comment]
Rebased and hopefully fixed. Please try again.

**Comment by yahiheb** [comment]
Still doesn't work properly for me.
https://github.com/zkSNACKs/WasabiDoc/pull/470#issuecomment-572056595

**Comment by yahiheb** [comment]
It still doesn't work for me guys, here is what I am doing:

- I checkout this PR
- I run `npm start`
- Go to http://localhost:8080/
- Search for who can use wasabi
- Click the result

The FAQ doesn't get collapsed.

If it works for you guys just ignore my comment.

**Comment by RiccardoMasutti** [comment]
@yahiheb I'll test tomorrow

**Comment by dennisreimann** [comment]
@yahiheb which OS and browser are you using?

**Comment by yahiheb** [comment]
Windows 7, Chrome and firefox.

**Comment by MaxHillebrand** [comment]
@yahiheb, then I found your bug, it's an easy fix:
1. Install Debian
2. Done, everything is fine now 
:laughing: 

But seriously, the dropdown does work for me although I do the exact same steps as you do @yahiheb ...

@dennisreimann this closes #476, it works for me at 31f0f954bdf74460e01b81460e66d4191a52ab4b!

**Comment by yahiheb** [comment]
> However, when I type in something to the search box, then click on the result, the results disappear, and when I then click in the search box again, they do not pop back up.

They don't pop back up because the search bar still has the focus. https://github.com/zkSNACKs/WasabiDoc/issues/476#issuecomment-573460413

**Comment by MaxHillebrand** [comment]
@dennisreimann is this ready to merge, with fresh PRs to fix the outstanding problems?
Though if @yahiheb says it is still not working for him...

**Comment by dennisreimann** [comment]
@MaxHillebrand Aside from what @yahiheb described what are the outstanding problems?

**Comment by yahiheb** [comment]
Great, it is working in production guys, thank you.
@dennisreimann do you think this https://github.com/zkSNACKs/WasabiDoc/pull/470/commits/7de6bbcab09375233f6bfa32beb527621874c755 was not necessary?

**Comment by dennisreimann** [comment]
Yes, I‘d try to revert this, as the previous state has a slightly better UX imho. But I can take care of that when I defocus the search field as you mentioned.

**Pull request merged**
