### PR TITLE
Add Google Search Console Verification

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Follows https://github.com/zkSNACKs/WalletWasabi/pull/3334

### CODE REVIEW

**Comment by yahiheb** [comment]
How would this benefit us?

**Comment by RiccardoMasutti** [comment]
@yahiheb Search Console tools and reports help you measure your site's Search traffic and performance, fix issues, and make your site shine in Google Search results.

**Comment by RiccardoMasutti** [comment]
https://github.com/zkSNACKs/WasabiDoc/issues/582

**Comment by yahiheb** [comment]
@RiccardoMasutti thank you for the clarification.
Is there any privacy concerns with this?
Just curious, what is `content: "JFhwCGTYfDv-U2qJwHzdovZaD4c-SoRGRTJuD_MF-x0"`

**Comment by MaxHillebrand** [comment]
@yahiheb apparently [no privacy concerns](https://github.com/zkSNACKs/WalletWasabi/pull/3334#issuecomment-603999892) and [here](https://github.com/zkSNACKs/WalletWasabi/pull/3334#issuecomment-604348189):
> content="ID"is a unique Google Search Console website ownership code.
> https://support.google.com/webmasters/answer/9008080#meta_tag_verification

**Comment by yahiheb** [comment]
Let's see what @dennisreimann thinks.

**Comment by dennisreimann** [comment]
yep, sure – benefits as outline by Riccardo :)

**Comment by yahiheb** [comment]
@lontivero Should this be merged or not? https://github.com/zkSNACKs/WalletWasabi/pull/3334#issuecomment-609470864

**Comment by lontivero** [comment]
> @lontivero Should this be merged or not? zkSNACKs/WalletWasabi#3334 (comment)

No @yahiheb, this meta tag is already available and it is one of those things that should not be in the code.

**Pull request closed without merging**
