### PR TITLE
Dark theme only

### PR DESCRIPTION
**Pull request by yahiheb**
Fixes https://github.com/zkSNACKs/WasabiDoc/issues/1226
Fixes https://github.com/zkSNACKs/WasabiDoc/issues/1211

IMO as of now we should just have dark theme, I don't know if this the best wat to do it or not, but it seems to work.

### CODE REVIEW

**Comment by yahiheb** [comment]
@CAnorbo What do you think about this?

**Comment by BTCparadigm** [comment]
cACK

**Review by MarnixCroes — APPROVED** [review]

**Comment by jesseaam** [comment]
NACK - messes up the left side bar.

<br><br>

## This is what is should look like
image

<br><br>

## This is what we see
image

**Review by BTCparadigm — APPROVED** [review]

**Comment by BTCparadigm** [comment]
@yahiheb which way? This or Norbo's PR?

**Comment by yahiheb** [comment]
Norbo's PR.

**Comment by MarnixCroes** [comment]
this can be closed

**Pull request closed without merging**
