### PR TITLE
Fix #1427

### LINKED ISSUE #1427: Navbar overlap on half screen
image

resizing fixes it, it happens again after refresh of page

### PR DESCRIPTION
**Pull request by CAnorbo**
Fixes #1427

### CODE REVIEW

**Review by yahiheb — COMMENTED** [review]
I cannot reproduce the issue neither on master nor with this PR.

@MarnixCroes Does this fix the issue for you?

**Comment by CAnorbo** [comment]
> I cannot reproduce the issue neither on master nor with this PR.
> 
> @MarnixCroes Does this fix the issue for you?

Resize it by about half and refresh the browser. Btw I made a fix #1574

**Comment by MarnixCroes** [comment]
> I cannot reproduce the issue neither on master nor with this PR.
> 
> @MarnixCroes Does this fix the issue for you?

I cannot test right now, change LGTM

**Review by MarnixCroes — COMMENTED** [review]
> I cannot reproduce the issue neither on master nor with this PR.
> 
> @MarnixCroes Does this fix the issue for you?

I cannot test right now, change LGTM

**Review by yahiheb — APPROVED** [review]
tACK

**Pull request merged**
