### PR TITLE
Change tag (Dojo.md)

### PR DESCRIPTION
**Pull request by yahiheb**
Second attempt to fix the issue #813

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
?

**Comment by MaxHillebrand** [comment]
Should we remove the All contributors in total?

**Comment by yahiheb** [comment]
> Should we remove the All contributors in total?

I agree with that, it will fix the issue I think, and also that list is not up to-date.
I will remove it.

**Comment by yahiheb** [comment]
Closing #823

**Pull request closed without merging**
