### PR TITLE
[WIP] A few words about Lurking Wife Mode

### PR DESCRIPTION
**Pull request by nopara73**
Please someone take over this PR from me. I am having difficulties from figuring out the syntax of the docs. The content is ready.

Refer: https://github.com/zkSNACKs/WalletWasabi/issues/2234

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
@nopara73 is it okay for you? #186

**Comment by nopara73** [comment]
@MaxHillebrand I cannot see this in docs.wasabiwallet.io, not sure why.

**Comment by yahiheb** [comment]
https://docs.wasabiwallet.io/using-wasabi/LurkingWifeMode.html

**Comment by nopara73** [comment]
I see, but I can't navigate to it in the menu.

**Comment by yahiheb** [comment]
#205 should fix that.

**Pull request merged**
