### PR TITLE
Bump .NET Core SDK version to the required version 3.1

### PR DESCRIPTION
**Pull request by MitchellCash**
As per this commit in the Wasabi Wallet repo https://github.com/zkSNACKs/WalletWasabi/commit/e6107829f8768b57aaf4d3cc80bbff9ecde427ee.

### CODE REVIEW

**Comment by MitchellCash** [comment]
@MaxHillebrand good idea! Added commit https://github.com/zkSNACKs/WasabiDoc/pull/462/commits/67dee0817e9af2479d66776c8cfec721ca72d3ac to the PR with the change.

**Comment by MitchellCash** [comment]
@MaxHillebrand I found an old references to v2.2 of the SDK that I originally missed. I cleaned that up and squashed my commit down (sorry for making you review again).

**Comment by MitchellCash** [comment]
@MaxHillebrand the other additional spot I could add the version is here:

https://github.com/zkSNACKs/WasabiDoc/blob/15967c81d2c3ad751d0675d3dcfe15a66c804a4c/docs/building-wasabi/HowToDebug.md#L18

Currently it just mentions "_.NET Core SDK_" without a version number. Would you like me to add a version number here?

**Comment by MaxHillebrand** [comment]
Thanks for the swift update, and also the effort to keep the branch clean!
Yes, [this](https://github.com/zkSNACKs/WasabiDoc/pull/462#issuecomment-571076247) is talking about requirements, so the most recent version should be added too, I think.

**Comment by MitchellCash** [comment]
@MaxHillebrand done (https://github.com/zkSNACKs/WasabiDoc/pull/462/commits/8a8d7387c09a6085c59010572f88981755a551bd)! Think I've got them all now 🚀

**Comment by yahiheb** [comment]
tACK

**Pull request merged**
