### PR TITLE
Update Logo_without_text_dark.png

### PR DESCRIPTION
**Pull request by MarnixCroes**
decrease pixel size to match the white one

to fix this, which is tupid

[Screencast from 05-06-2023 14:09:24.webm](https://github.com/zkSNACKs/WasabiDoc/assets/93143998/50d69f6f-400f-43cf-9919-6b51227a84ab)

### CODE REVIEW

**Comment by MarnixCroes** [comment]
cc @CAnorbo 
(I cannot add you as reviewer?)

**Comment by CAnorbo** [comment]
> 

I'm just  pleb!

**Comment by MarnixCroes** [comment]
images were made same size, now they also have some position 
kudos to @CAnorbo for last fix

**Comment by CAnorbo** [comment]
tACK

**Pull request merged**
