### PR TITLE
Questions

### PR DESCRIPTION
**Pull request by Zolgarr**
So I'm reading through the docs to see if there's anything I don't understand.

I was reading the "CAN I HURT MY PRIVACY USING WASABI?" on the FAQ on the website:
https://wasabiwallet.io/#faq

The second sentence goes like this:

"It is crucial to understand that Wasabi is not a fool-proof solution if you neglect to practice coin control after the mixing process."

The questions immediately raised in me:
1. Okay, so how to do it right?
2. What exactly is coin control?

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
Please post an issue here: https://github.com/zkSNACKs/WasabiDoc/issues instead of opening a PR.

Ps: you can find Coin Control Best Practices here: https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#coin-control-best-practices

**Comment by Zolgarr** [comment]
Okay, will do!

**Comment by yahiheb** [comment]
Here are some links that might answer your questions:

https://medium.com/@nopara73/coin-control-is-must-learn-if-you-care-about-your-privacy-in-bitcoin-33b9a5f224a2
https://docs.wasabiwallet.io/using-wasabi/Receive.html#coin-control
https://docs.wasabiwallet.io/FAQ/FAQ-UseWasabi.html#why-is-coin-control-so-important

**Comment by Zolgarr** [comment]
Thank you.

**Pull request closed without merging**
