### PR TITLE
Updated WasabiDoc/README.md

### PR DESCRIPTION
**Pull request by CryptoRafe**
Added the three main pillars and links to them for easier navigation. Could also add a small description about each?
Also changed spacing and few words.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
Thanks Rafe! 
I like it :)

- [ ] Can you maybe add a [short explanation](https://github.com/zkSNACKs/WasabiDoc/issues/31) for what the three pillars are? 
- [ ] And please add a link to the [FAQ](https://github.com/zkSNACKs/WasabiDoc/tree/master/docs/FAQ) as well

**Comment by thunderBiscuit** [comment]
ACK. I like this.

**Comment by CryptoRafe** [comment]
Added a short explanation.
FAQ link should already be there 
Corrected typos, thanks for pointing them out :)

**Comment by CryptoRafe** [comment]
Ah damn, made a mistake and copied a bit of the wrong section. Fixing it now

**Comment by MaxHillebrand** [comment]
Great stuff, thanks @CryptoRafe for writing and thanks @thunderBiscuit for the ACK.

**Comment by thunderBiscuit** [comment]
@CryptoRafe I don't know if it's your first contribution to a major bitcoin project or if you simply have a brand new GitHub account, but in case it's the former, congrats on your first PR!

**Comment by CryptoRafe** [comment]
@thunderBiscuit 
Yes it is, thanks!
New to GitHub :) Slow and steady learning

**Comment by thunderBiscuit** [comment]
Awesome @CryptoRafe . We're glad to have you on board.

As an aside, I thought I'd share a tip for working with forks. In general, you'll find your fork always "out-of-date" with the main repo, because new PRs are being merged all the time. If you don't want to have to delete and open a new fork all the time, here is how to go about it.

Once you've forked the repo, you have a repo under your name that is a fork of the main one. When you clone it locally to your machine, git then interprets that remote (your fork) as the "origin" repo, the one default repo against which it will push and pull. So when @MaxHillebrand for example merges a PR on the main repo, a normal `git pull` will not bring those changes into your local repo because you are basically asking to pull on your remote version (the forked version), and that has not incorporated any changes since you made the fork. Instead, in order to get the latest changes, you can ask git to pull from the main WasabiDoc repo using
```bash
git pull https://github.com/zkSNACKs/WasabiDoc.git master
```
 (notice the master option there at the end too; you could pull from any branch).

This way, you can make a single fork of a repo you will contribute to often and just keep it evergreen by always starting your session with a fresh pull from the main repo. If you have conflicts, you'll have to deal with them before the pull can be completed, but that's another thing entirely. Hope this helps! I just know git and github can really be a maze to navigate at first.

**Comment by CryptoRafe** [comment]
Thanks for the tips @thunderBiscuit ! 
They are indeed needed. Lots of things for me to learn.
I'll try that evergreen fork thingy asap.

**Pull request merged**
