### PR TITLE
Update Dojo

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Move All Contributors on top and move 'old Dojo' on the bottom

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
@all-contributors please add @PulpCattel for doc

**Comment by RiccardoMasutti** [comment]
@all-contributors please add @xavierfiechter for doc

**Comment by RiccardoMasutti** [comment]
Please help me to match the all-contributors list with users from Dojo

**Comment by yahiheb** [comment]
Why would you do that?
All-contributors list if for people who contributed to the doc repo, Dojo is something else.

**Comment by RiccardoMasutti** [comment]
> Why would you do that?
> All-contributors list if for people who contributed to the doc repo, Dojo is something else.

Mmmh... Though we wanted to replace Dojo with SourceCred/All Contributors. Maybe I'm wrong:
#6 #8 #124

**Comment by MaxHillebrand** [comment]
The All Contributor bot is for anyone who has done even a minor contribution like a typo fix or bug fix. The dojo belts are earned by those who really did outstanding contributions so that a higher belt wants to give them extra recognition. So I say we keep both, and I don't mind that all contributors are at the top. 

I give ACK to merge, what about the others?

**Comment by MaxHillebrand** [comment]
So do I merge this?
I'd like to get one more ACK from you others before I do.

**Comment by RiccardoMasutti** [comment]
> So do I merge this?
> I'd like to get one more ACK from you others before I do.

@yahiheb @molnard ?

**Comment by MaxHillebrand** [comment]
Closing because the Dojo should be above the All Contributors list.

**Pull request closed without merging**
