### PR TITLE
Update IntroWasabi.md

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Following #255 and #256

Fixes everything that was still wrong or broken

### CODE REVIEW

**Comment by yahiheb** [comment]
What things that were broken or not working in that file?
Have you tried your proposed changes? https://github.com/RiccardoMasutti/WasabiDoc/blob/patch-66/docs/IntroWasabi.md
Things are broken now and now well formatted.

**Comment by RiccardoMasutti** [comment]
> NACK.
> What things that were broken or not working in that file?
> Have you tried your proposed changes? https://github.com/RiccardoMasutti/WasabiDoc/blob/patch-66/docs/IntroWasabi.md
> Things are broken now and not well formatted.

Fixed with  </br> the submenus.

I deleted `Features` by mistake.

**Comment by yahiheb** [comment]
Again go to https://github.com/RiccardoMasutti/WasabiDoc/blob/patch-66/docs/IntroWasabi.md and test your proposed changes.

**Comment by RiccardoMasutti** [comment]
> Again go to https://github.com/RiccardoMasutti/WasabiDoc/blob/patch-66/docs/IntroWasabi.md and test your proposed changes.

Fixed. ty

**Comment by MaxHillebrand** [comment]
Is this ready to merge?

**Comment by RiccardoMasutti** [comment]
> Is this ready to merge?

Yes it is

**Pull request merged**
