### PR TITLE
Create robots.txt

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Search Engine Optimization: https://support.google.com/webmasters/answer/6062596?hl=en

Follows https://github.com/zkSNACKs/WalletWasabi/pull/4276

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
I don't know.
Will merge when there is consensus and it is merged in `/WalletWasabi/`.

**Comment by RiccardoMasutti** [comment]
It is merged

**Comment by MaxHillebrand** [comment]
ftr, @yahiheb N/ACK?

**Comment by yahiheb** [comment]
> ftr, @yahiheb N/ACK?

I don't know either, but since it was merged in the main repo I guess it is useful and safe to merge.

**Pull request merged**
