### PR TITLE
Revert "Fix danger message"

### PR DESCRIPTION
**Pull request by MaxHillebrand**
Reverts zkSNACKs/WasabiDoc#929

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
I don't want to merge this one prematurely too! :smile: 

@yahiheb @RiccardoMasutti, can you please check locally that now on master branch the tip box is not aligned, and with this PR, it is aligned again?

**Comment by yahiheb** [comment]
NACK. that PR shouldn't be reversed.

Master:
Capture1

This PR:
Capture2

**Comment by yahiheb** [comment]
Also please don't create new branches in this Repo.

**Comment by MaxHillebrand** [comment]
that's odd - but I can reproduce your screenshots - thanks @yahiheb for the catch. Master branch is good.

> Also please don't create new branches in this Repo.

ftr, I used GitHub UI revert button, and it apparently creates a branch in this repo... good to know, will not use the feature in the future.

**Pull request closed without merging**
