### PR TITLE
RPC: specify wallet in request path

### PR DESCRIPTION
**Pull request by MarnixCroes**
closes https://github.com/zkSNACKs/WasabiDoc/issues/1494

### CODE REVIEW

**Review by yahiheb — CHANGES_REQUESTED** [review]
This tip is valid for all methods that can be used with a wallet so it should be added separately, either at the top or bottom.

Also add an example how to do this, like in https://github.com/zkSNACKs/WalletWasabi/pull/10522#issue-1673583899

**Review by MaxHillebrand — COMMENTED** [review]
I guess this should be updated consistantly for other calls too

**Comment by MarnixCroes** [comment]
> it should be added separately

pushed

> I guess this should be updated consistantly for other calls too

current is ok? Or do you mean to update all RPC request examples by including the specified wallet?

**Comment by MaxHillebrand** [comment]
> Or do you mean to update all RPC request examples by including the specified wallet?

Yes, can be a follow up pr

**Review by yahiheb — APPROVED** [review]
LGTM

**Pull request merged**
