### PR TITLE
Wasabi Wallet 2.0 Documentation

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
Nice, finally :)

Is there a link to the way back machine archive for the 1.0 doc?

**Comment by yahiheb** [comment]
> Is there a link to the way back machine archive for the 1.0 doc?

I created this docs-1.0 branch https://github.com/zkSNACKs/WasabiDoc/tree/docs-1.0

**Review by MarnixCroes — APPROVED** [review]
LGTM

**Comment by MaxHillebrand** [comment]
A link to the "raw" github branch isn't really useful for basic users, they should see the build/deployed graphical docs, and for this the way back machine is the least work intensive solution.

Please link to this most recent snapshot
https://web.archive.org/web/20220804041943/https://docs.wasabiwallet.io/

**Review by BTCparadigm — APPROVED** [review]
LGTM

**Pull request merged**
