### PR TITLE
Remove License file in docs folder

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
But why?
I'd like to show the license in the docs as well.

**Comment by yahiheb** [comment]
But isn't that redundant? Why do we need it in the docs folder?

**Comment by MaxHillebrand** [comment]
I mean - it should be shown in the docs website that Wasabi is MIT license, otherwise it's only in the github repo.

**Comment by MaxHillebrand** [comment]
I've fixed that the license was missing in the side bar.
closing this now :)

**Comment by yahiheb** [comment]
But can't you use the other license file?

**Comment by MaxHillebrand** [comment]
no, because it's not in the /docs/ repo...

**Pull request closed without merging**
