### PR TITLE
Use PGP public key consistently

### PR DESCRIPTION
**Pull request by yahiheb**
Use `PGP public key` instead of `key` or `PGP key` or `public key`.

### CODE REVIEW

**Comment by dennisreimann** [comment]
Might also be a use case for a specific [variable](https://github.com/zkSNACKs/WasabiDoc#variables).

**Comment by yahiheb** [comment]
> Might also be a use case for a specific variable.

But this will not change over time.

**Comment by dennisreimann** [comment]
> But this will not change over time.
Correct, but this way we would ensure that there's a single source of truth.

**Comment by dennisreimann** [comment]
I totally missed that this is primarily a wording change and not about the PGP key itself. Sorry for that! (Nevertheless we might want to use a variable for the key itself).

**Pull request merged**
