### PR TITLE
Downgrade markdown-it-emoji

### PR DESCRIPTION
**Pull request by CAnorbo**

### CODE REVIEW

**Review by molnard — CHANGES_REQUESTED** [review]
The title says downgrade, but in package.json it looks like an addition. Can you elaborate a bit more what happened here? Now that the high severity issues solved by your other PR is it still worth to merge this?

**Review by yahiheb — APPROVED** [review]
```
$ npm start

> wasabidoc@0.1.0 prestart
> rm -rf $npm_package_config_dist


> wasabidoc@0.1.0 start
> vuepress dev docs

node:internal/modules/cjs/loader:1144
  const err = new Error(message);
              ^

Error: Cannot find module 'markdown-it-emoji/lib/data/full.json'
Require stack:
- C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\shared-utils\lib\parseEmojis.js
- C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\shared-utils\lib\parseHeaders.js
- C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\shared-utils\lib\deeplyParseHeaders.js
- C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\shared-utils\lib\index.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (C:\Users\chihe\OneDrive\Bureau\WasabiDoc\node_modules\@vuepress\shared-utils\lib\parseEmojis.js:6:37)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\chihe\\OneDrive\\Bureau\\WasabiDoc\\node_modules\\@vuepress\\shared-utils\\lib\\parseEmojis.js',
    'C:\\Users\\chihe\\OneDrive\\Bureau\\WasabiDoc\\node_modules\\@vuepress\\shared-utils\\lib\\parseHeaders.js',
    'C:\\Users\\chihe\\OneDrive\\Bureau\\WasabiDoc\\node_modules\\@vuepress\\shared-utils\\lib\\deeplyParseHeaders.js',
    'C:\\Users\\chihe\\OneDrive\\Bureau\\WasabiDoc\\node_modules\\@vuepress\\shared-utils\\lib\\index.js'
  ]
}

Node.js v20.10.0
```

This PR solves the above error that we have on master.

tACK.

**Comment by yahiheb** [comment]
> Now that the high severity issues solved by your other PR is it still worth to merge this?

Yes because there is an error on the server and if you run master locally.

**Comment by yahiheb** [comment]
Just a note, when I run this I get some warnings, but everything seems to work well:

image

**Comment by molnard** [comment]
@yahiheb do we have emojis that could be related to the "downgraded" library - and check of those are OK? I am not sure if there is something to check or not you know docs the best.

**Comment by CAnorbo** [comment]
This shouldn’t be an issue, I think we used this older version before my yesterday's PRs. Also, it’s not less emojies only some code changes or dependencies.

**Comment by yahiheb** [comment]
I am not aware of any emojis used in the docs, and as Norbo said I don't think there is any issue with that.

**Pull request merged**
