### PR TITLE
Accent color fix

### PR DESCRIPTION
**Pull request by CAnorbo**
Fix for #1404

### CODE REVIEW

**Review by MarnixCroes — APPROVED** [review]
ACK

**Review by yahiheb — DISMISSED** [review]
This does not fix the issue.

image

**Review by yahiheb — CHANGES_REQUESTED** [review]
@CAnorbo This fixes the issue but first you have to update your branch to master.

**Comment by yahiheb** [comment]
I don't know why but this doesn't seem to fix the issue for me. Maybe because of some cache.

**Comment by CAnorbo** [comment]
> I don't know why but this doesn't seem to fix the issue for me. Maybe because of some cache.

Interesting. If you run **npm start** it should recreate the CSS file automatically, but if I remember well you had the same issue with the previous changes too.

**Comment by yahiheb** [comment]
> > I don't know why but this doesn't seem to fix the issue for me. Maybe because of some cache.
> 
> Interesting. If you run **npm start** it should recreate the CSS file automatically, but if I remember well you had the same issue with the previous changes too.

I don't know, I tried a couple of times and the issue still exists.
@MarnixCroes can you test his PR?

**Pull request merged**
