### PR TITLE
Add Tor Guard Node FAQ

### PR DESCRIPTION
**Pull request by RiccardoMasutti**

### CODE REVIEW

**Comment by nopara73** [comment]
Where did I say this?

**Comment by MaxHillebrand** [comment]
@nopara73 in person, while in the office, then I [and Lucas too] answered this question in the telegram group.

**Comment by nopara73** [comment]
Please remove this. This is not a question anyone in his right mind would ever ask and I don't even think the answer (maybe even the question) is correct.

**Comment by MaxHillebrand** [comment]
well... somebody actually did ask it... :laughing: 
But agreed, it's for sure not "frequently" asked.

**Comment by yahiheb** [comment]
> Please remove this. This is not a question anyone in his right mind would ever ask and I don't even think the answer (maybe even the question) is correct.

> well... somebody actually did ask it... laughing
> But agreed, it's for sure not "frequently" asked.

This is why I have said [previously](https://github.com/zkSNACKs/WasabiDoc/pull/613#issuecomment-599212803) we shouldn't keep adding questions just for the sake of adding them, specially reddit or telegram questions.
We should be more selective on what should go in the docs, to avoid adding things and then removing them, as we have been doing lately.

**Pull request merged**
