### PR TITLE
[release] update CJ output count to 10

### PR DESCRIPTION
**Pull request by MarnixCroes**
https://github.com/zkSNACKs/WalletWasabi/pull/10813

### CODE REVIEW

**Comment by MarnixCroes** [comment]
@MaxHillebrand 
I wasn't aware of that detail, thanks for sharing

**Comment by yahiheb** [comment]
> FYI, in most cases you will register 8 or less, only some edge case whales will register 10.

This is worth mentioning imo.

**Comment by MaxHillebrand** [comment]
> > FYI, in most cases you will register 8 or less, only some edge case whales will register 10.
> 
> This is worth mentioning imo.

Already getting 8 outputs is not likely, getting 9 or 10 has further decreasing likely hood.

I'm not sure if the details of the different internal decomposer have to be explained in this FAQ.

**Comment by MarnixCroes** [comment]
> Already getting 8 outputs has low likely hood, getting 9 or 10 has further decreasing likely hood.
> 
> I'm not sure if the details of the different internal decomposer have to be explained in this FAQ.

Indeed.
This change is not aimed for whales/ has a whale requirement (min x BTC), but it is likely to be used by whales.
i.e. for example in a round there is one whale and multiple plebs, the whale can now further "split" his coins for better privacy/less likely to have a whale output.

**Review by yahiheb — APPROVED** [review]

**Pull request merged**
