### PR TITLE
Fix JoinMarket capitalization.

### PR DESCRIPTION
**Pull request by nopara73**
Also testing CodeScene CI if it makes sense here.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
I'm actually not sure what the proper spelling is... the Joinmarket github says both `JoinMarket` and `Joinmarket` rather inconsistently.

**Comment by nopara73** [comment]
image

**Comment by MaxHillebrand** [comment]
I believe I got all the `Joinmarket` and made them upper case to `JoinMarket` [I used `git grep`].

Though I did not yet rename the file `using-wasabi/Joinmarket.md` to `using-wasabi/JoinMarket.md`, as this would break links. Should I change it too and fix all internal links?

**Comment by nopara73** [comment]
> Should I change it too and fix all internal links?

No.

**Pull request merged**
