### PR TITLE
[BUILDING] remove contribution game

### PR DESCRIPTION
**Pull request by MaxHillebrand**
The contribution game is over, and it seems there won't be a new one in the foreseeable future. So we should remove it for now, and when it comes back it should be added properly again.

I will merge when concept ACK from others.

### CODE REVIEW

**Comment by yahiheb** [comment]
Noooo don't do it, it was the beginning of my journey with Wasabi.
Seriously now, I think it should be kept as a reference and as part of Wasabi's history trying to find new innovative ways to attract and incentivise new contributors.

**Comment by MaxHillebrand** [comment]
hahaha I remember thinking like "who is this @yahiheb and why does he all of a sudden make so many typo fixes - this is awesome!!! [and a pain to review :laughing:]"

 Ok, but then we should re-write this document instead to make clear what it was and that it is no longer active.

**Comment by MaxHillebrand** [comment]
I'm closing this in favor of a re-writing of what the contribution game is, and the history of the first one.

FYI, we are maybe going to do a [new contribution game for reviewing v1.1.10](https://github.com/zkSNACKs/WalletWasabi/issues/2631) so this chapter is very relevant still, but it should be written in general.

**Comment by MaxHillebrand** [comment]
Closed in favor of #352

**Pull request closed without merging**
