### PR TITLE
[GLOSSARY] segwit

### PR DESCRIPTION
**Pull request by MaxHillebrand**
adds glossary on segwit

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
NACK.
Should be `Bech32` synonymous imho.

**Comment by MaxHillebrand** [comment]
> Should be added as Bech32 synonymous. - @RiccardoMasutti 

No, bech32 =/ segwit. bech32 is an encoding standard, which is also used elsewhere. For example taproot addresses will also be bech32 encoded.

**Comment by RiccardoMasutti** [comment]
> > Should be added as Bech32 synonymous. - @RiccardoMasutti
> 
> No, bech32 =/ segwit. bech32 is an encoding standard, which is also used elsewhere. For example taproot addresses will also be bech32 encoded.

Yes I agree with that, but I'm thinking like a newbie.

**Comment by MaxHillebrand** [comment]
> I'm thinking like a newbie.

A newbie will like to have a correct two sentence explanation tl,dr of what segwit is...

**Pull request merged**
