### PR TITLE
update FAQ Daemon

### PR DESCRIPTION
**Pull request by MarnixCroes**
merge after https://github.com/zkSNACKs/WasabiDoc/pull/1509

### CODE REVIEW

**Comment by MarnixCroes** [comment]
@turbolay this one line of change is waiting for review yes :D

**Comment by yahiheb** [comment]
To avoid the confusion, this change sould have been done in the other PR.

**Comment by MarnixCroes** [comment]
> To avoid the confusion, this change sould have been done in the other PR.

what confusion

**Comment by MarnixCroes** [comment]
@turbolay I kept all PR's for release in draft, to prevent them from being merged

**Pull request merged**
