### PR TITLE
Build docs with Vuepress

### PR DESCRIPTION
**Pull request by dennisreimann**
This is an alternative build approach than what was layed out in #2.

I talked to @MaxHillebrand and @thunderBiscuit about the advantages VuePress has over GitBook, namely:

- it lets you build the project locally and see changes immediately
- it is more flexible in terms of adapting the layout
- the resulting site is more performant and usable offline
- it is open source, whereas GitBook takes the commercial route nowadays

I have set up VuePress on this branch and would incorporate your feedback. 
The project README now also contains the setup instructions you need to run the docs locally.

Prerequisite: Node.js needs to be installed.

### CODE REVIEW

**Comment by dennisreimann** [comment]
We got this set up for @MaxHillebrand and he will be testing this. In case we can decide on using this, I could go ahead, do some of the layout adjustments and take care of the deployment.

**Comment by MaxHillebrand** [comment]
Thanks @dennisreimann!!

I have a local instance up and running, I really like that it can be build locally.
It looks very nice visually already, and it seems that there are many ways to customize it further.

I'll play around with it some more, but because of the reasons described above, at first glance I think that VuePress > GitBook.

**Comment by MaxHillebrand** [comment]
Haha - what I like most about it so far, is that my dark-mode firefox plug-in work with it - because it does not for GitBook :laughing:

Same question as in #14, how should we best add the images? A local `/img/` directory, or work with imgur as in the main repo?

**Comment by dennisreimann** [comment]
> how should we best add the images?

You can put them into `docs/.vuepress/public/`, that's where I have placed the logos already.

Referencing them then can be done by using `/image.png` (or `/folder/image.png` in case you want to structure them further in the public dir).

**Comment by dennisreimann** [comment]
Regarding the navigation structure in the topbar and sidebar: Some of the thinsg that cannot be configured via the file structure are set in ` docs/.vuepress/config.js` – the detailed docs for that are in the [VuePress default theme config](https://vuepress.vuejs.org/default-theme-config/).

**Comment by MaxHillebrand** [comment]
The `dennisreimann:vuepress` branch is build live [here](https://wasabi.incodewetrust.com/). 

Ready for review!

**Comment by MaxHillebrand** [comment]
Can you please remove the `SUMMARY.md` file, I think this is only used by GitBook, but please confirm @thunderBiscuit.

**Comment by mayankchhabra** [comment]
+1 for local builds, will be much more efficient to preview when styling, theming and structuring vs GitBook.

**Comment by thunderBiscuit** [comment]
ACK.

**Comment by dennisreimann** [comment]
I also added the deployment scripts – we can hook all of that up and deploy to the actual domain once we decided where this should go.

**Comment by thunderBiscuit** [comment]
Once this is merged we can start working on the structure. Mostly the `config.js` file needs a bit of love in order to create the sidebars that will make the site more useable.

**Comment by MaxHillebrand** [comment]
Fantastic work peers!!

Thanks for preparing the deployment @dennisreimann!
You're right @thunderBiscuit, the structure needs to be fine tuned, and that should happen sooner rather than later. I think we should continue the discussion on slack to condense a couple ideas, then open a new issue with a detailed proposal, and then present it at mondays dev-call to get feedback.

**Comment by MaxHillebrand** [comment]
Ok, we can compare the two now!!

[GitBook](https://zksnacks.gitbook.io/wasabidoc/) and [VuePress](https://wasabi.incodewetrust.com/)

**Comment by thunderBiscuit** [comment]
I suggest merging this on a special vuepress branch. The `deploy.sh` script will force push to a new branch called `gh-pages`, which we then set the repo to track and deploy as gitpages. The two implementations (GitBook and VuePress) can easily coexist for for now, at least for the time it will take us to pick a winner.

**Comment by MaxHillebrand** [comment]
Mhhh, but this PR does delete the GitBook stuff...
idk, but I think it is better to wait the two more days till the dev-call where we will make the decision between GitBook [close PR] and VuePress [merge PR].

**Comment by MaxHillebrand** [comment]
I resolved some conflicts of the change to consistent "CoinJoin" spelling in #28.
I think this branch is clean now - but I might have messed up with the vuepress header of the `/docs/README.md` - can someone please review?

**Comment by thunderBiscuit** [comment]
The `docs/README.md` is now being used for the landing page instead of the first page of the documentation per se (which is now `GettingStarted.md`). By adding to the readme file, we are simply creating a super long landing page. I assume that might not have been your intention.

**Comment by MaxHillebrand** [comment]
Yes, we should structure the repo so that it fits VuePress, it makes of course sense to have the `README.md` now be the landing page - which looks really really cool, and I think we can do a lot with this.
The `GettingStarted.md` file looks good :)

**Pull request merged**
