### PR TITLE
delete technical overview

### PR DESCRIPTION
**Pull request by MarnixCroes**
closes https://github.com/zkSNACKs/WasabiDoc/issues/1371

previous attempts to update this didn't make it https://github.com/zkSNACKs/WasabiDoc/pull/1087 https://github.com/zkSNACKs/WasabiDoc/pull/1029

### CODE REVIEW

**Comment by MarnixCroes** [comment]
I just noticed that `API` in the  WalletWasabi README.md links to this

**Review by yahiheb — CHANGES_REQUESTED** [review]
How about we simply remove this whole document.

**Comment by yahiheb** [comment]
> I just noticed that `API` in the WalletWasabi README.md links to this

https://github.com/zkSNACKs/WalletWasabi/pull/10549 fixes this.

**Comment by yahiheb** [comment]
> > I just noticed that `API` in the WalletWasabi README.md links to this
> 
> [zkSNACKs/WalletWasabi#10549](https://github.com/zkSNACKs/WalletWasabi/pull/10549) fixes this.

https://github.com/zkSNACKs/WalletWasabi/pull/10549 was merged.

**Comment by MarnixCroes** [comment]
what's up with this, 6 months later and it's still here...
remove the full thing?

**Comment by MaxHillebrand** [comment]
> what's up with this, 6 months later and it's still here...
> remove the full thing?

Yup

**Review by MaxHillebrand — APPROVED** [review]

**Comment by MarnixCroes** [comment]
merging, shouldn't be controversial.
If someone thinks we should really have this we could add it back, current is too outdated anyway.

**Pull request merged**
