### PR TITLE
Remove duplicate license

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
I agree with Max

**Comment by yahiheb** [comment]
> I think the license should be in the rendered documentation too

What is the reason for that? I really don't see why it should be there.
Also you need to maintain it separately .

**Comment by MaxHillebrand** [comment]
It should be there so that users can read it inside the documentation, without going either to the "confusing" github UI, or to the "official" license website. 

I don't think maintenance is an issue though, the license doesn't change, only the year, and that'll be easily done once a year...

**Comment by lontivero** [comment]
I agree with @yahiheb, it is just one link.

**Pull request merged**
