### PR TITLE
Update ChangeCoins.md

### PR DESCRIPTION
**Pull request by davterra**
I saw Riccardo's "help wanted" tag on this, and waded through it, making changes that I thought made it more clear, and also correcting several spelling, punctuation, and grammatical errors.

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
Please propose new `ChangeCoins.md` content directly in #459 as a review.

It's better if we keep things separate and you open a dedicated PR for typos.

**Comment by davterra** [comment]
Ok, this is my first ever PR. Sorry to need a bit of hand-holding, but I only submitted 1 file change: ChangeCoins.md
I will try to figure this out on my own, but ATM I have no idea how this PR turned into a proposed change for 3 files. I made a branch of the current master, made local changes to ChangeCoins.md and pushed them to my related branch on github, then submitted this PR based on that branch.

**Comment by RiccardoMasutti** [comment]
Yeah I noticed that. Your commit are 5 months old.

You shoudl create a new updated branch and work there

**Comment by davterra** [comment]
> Yeah I noticed that. Your commit are 5 months old.
> 
> You shoudl create a new updated branch and work there

I thought that was exactly what I did. Anyway, if you think it is better to just work through the existing #459 I will submit my change there. My changes are not a total re-write, but do include some significant re-wording. It seems redundant to open a separate PR for grammar etc. changes, if that is all also accomplished in my re-write

**Comment by RiccardoMasutti** [comment]
Please open a review and propose new/updated content directly in #459 so we can valuate it.

**Comment by yahiheb** [comment]
Better to fork the repo again, checkout a new branch, make your local changes, commit them, push them to your GitHub repo, then make the PR.

**Comment by MaxHillebrand** [comment]
Awesome, thanks for your first ever PR @davterra!!! Git is confusing on first sight, so no worries at all. I see you have made a review with change suggestions, that is the way to go when a topic is under development.

**Pull request closed without merging**
