### PR TITLE
Add const variable for zkSNACKs public key fingerprint

### PR DESCRIPTION
**Pull request by yahiheb**

### CODE REVIEW

**Comment by PulpCattel** [comment]
There's one also in WasabiSetupTails.md

**Comment by yahiheb** [comment]
@MaxHillebrand please be careful when solving conflicts, sometimes you have to combine the diffs to not override someone's changes.

**Comment by molnard** [comment]
@MaxHillebrand always check the CI before merge. I can set the repo CI to be mandatory to pass before merging. Is that ok?

**Comment by yahiheb** [comment]
@molnard The comma problem was my mistake.

**Comment by molnard** [comment]
It was a settings mistake. Now, one cannot merge until the CI tests not passed.

**Pull request merged**
