### PR TITLE
Add structured data to FAQs

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Follows https://github.com/zkSNACKs/WalletWasabi/pull/2326

Marking up content on Wasabi Documentation website can:
- Lead to the generation of rich snippets in search engine results like the one showed down here
- Enhance CTR (Click Through Rate) from the search result
- Provide greater information to search engines to improve their understanding of the content on Wasabi website

As specified on [https://developers.google.com/search/docs/data-types/faqpage](https://developers.google.com/search/docs/data-types/faqpage)

Test code: https://search.google.com/structured-data/testing-tool

Final result:
image

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
I specifically excluded `FAQ-UseWasabi.md`; waiting for https://github.com/zkSNACKs/WasabiDoc/pull/613

**Comment by RiccardoMasutti** [comment]
@MaxHillebrand Properly marked up FAQ pages may be eligible to have a rich result on Search and an Action on the Google Assistant, which can help Wasabi site reach the right users. The screenshot above is an example of an FAQ rich result.

FAQ rich results are available in all countries and languages where Google Search is available. The feature is available on desktop and mobile devices.

Please read: https://support.google.com/webmasters/answer/7358659

**Comment by MaxHillebrand** [comment]
Yes @dennisreimann, this seems to clutter the markdown quite a bit... 
I am not sure why @RiccardoMasutti closed #395 

Can you please explain more the difference in approach of #395 and #641? @dennisreimann, what would have to be tweaked for #395 to make it work only for FAQ containers?

**Comment by RiccardoMasutti** [comment]
I agree with you guys. 3 months ago @dennisreimann and I talked a lot to understand how to implement it by editing the structure files, it would be the best solution.

I could not do it, can you give me a hand?

**Comment by RiccardoMasutti** [comment]
Ps: we need to add 
`	<div itemscope itemtype="https://schema.org/FAQPage">` on top of FAQ pages and close the `</div` at the bottom

**Comment by yahiheb** [comment]
> I am not sure why @RiccardoMasutti closed #395 

I am not sure either why it was not closed.

> #395 is not complete

If that is the case then it should have been kept open to complete it later on.

**Pull request closed without merging**
