### PR TITLE
New Writing Convention: Each sentence new line

### PR DESCRIPTION
**Pull request by MaxHillebrand**
This is a PR based on a suggestion by @dennisreimann to write this documentation with a simple, yet powerful convention:

### Each sentence starts a new line.

Why is this useful?

- Easy to spot too long, or too short sentences
- Changes to a sentence are only affect that line
- The `line addition and deletion` metric is meaningful again

### A regular paragraph looks like this in the mark down file:

```
foo.
bar.
foo.
```

and this renders to:
> foo. bar. foo.

### A line break is coded like this:

```
foo.
bar.

foo.
bar.
```

or

```
foo.
bar. </br>
foo.
bar.
```

and this renders to:
> foo. bar.
> foo. bar.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
I know, this is a pain to review...

Haha, if you want to save your self the trouble, you gotta trust me... :fearful:

I did mainly change the line thing.
But also some minor typos that I found.
Added a couple hyperlinks.

Everything looks fine on my local vuepress build, so I am comfortable with merging, if there's a ConceptACK.

**Comment by thunderBiscuit** [comment]
I have never tried writing markdown using this convention but it sounds like it would keep things clean and easier to change. ConceptACK on my side.

**Comment by dennisreimann** [comment]
> I know, this is a pain to review...
> Haha, if you want to save your self the trouble, you gotta trust me...

This is lies, my trust in you is… oh wait, looks goods to me 😁👌

**Comment by thunderBiscuit** [comment]
I think the official saying is "don't verify, trust @MaxHillebrand ".

**Pull request merged**
