### PR TITLE
Fix clickable elements too close together

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
Following #878. Error still appears on GSC

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
It should be fixed now. Unfortunately I cannot test it locally, as I need to test with GSC's Google Mobile Crawler

**Review by MaxHillebrand — APPROVED** [review]
What did you change now that should make it work?

ACK, let's see if it works after merge.

ping @yahiheb

**Comment by RiccardoMasutti** [comment]
> What did you change now that should make it work?
> 
> ACK, let's see if it works after merge.
> 
> ping @yahiheb

-3 pixels of margin property between FAQs

**Comment by yahiheb** [comment]
> It should be fixed now. Unfortunately I cannot test it locally, as I need to test with GSC's Google Mobile Crawler

It should be tested so we don't have to create another PR in 2 months.

**Comment by RiccardoMasutti** [comment]
> > It should be fixed now. Unfortunately I cannot test it locally, as I need to test with GSC's Google Mobile Crawler
> 
> It should be tested so we don't have to create another PR in 2 months.

Unfortunately I cannot test it locally, I need to update documentation, go to Google Search Console and start tests again

**Comment by RiccardoMasutti** [comment]
@yahiheb @MaxHillebrand let's merge it so I can test with GSC

**Pull request merged**
