### PR TITLE
Prepare repo for initial GitBook deployment

### PR DESCRIPTION
**Pull request by thunderBiscuit**
This PR restructures the repo so that an initial GitBook deployment will generate at least a small functioning website. To integrate the other files currently in the docs directory into the website, one simply has to go and modify the `SUMMARY.md` file. That's where all the juice is. Note that once the webhook between the repo and GitBook is created, the website will regcompile every time a commit is made on the `docs/` directory.

Note that I brought the README file into the docs directory, but created a new, smaller one for the root of the repo.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
Great, thanks for the restructure and setup!!

One thing, I created a bunch of hyper links within the repo, and they are for example `/FAQ/FAQ-Introduction.md#what-is-a-coin-join`.
Your PR changes the repo structure, so we must change the links to `docs/FAQ/FAQ-Introduction.md#what-is-a-coin-join`, adding `docs/` up front.

Can you change this in your local branch, and then push the correct to master?
I'll fix my open PR #10.

**Comment by thunder-B** [comment]
Ah yes good point. I'm actually not sure how gitbook interprets those, I'll have to test; I know, for example, that the `.gitbook.yaml` file declares the "root" of the book to be the `docs/` directory. Does that mean the links also operate under that structure/assumption? I believe so, but let me check first. I'll test on the mock repo.

**Comment by thunderBiscuit** [comment]
So I tested the links when generated by GitBook using my [mock repo](https://app.gitbook.com/@wasabi-test/s/wasabi-docs-test/gitbook-tests/links) and they work!

I think they make it that way so that the GitBook docs generated are "self-contained" in a way, and so for example you could move the whole docs directory around and none of the links would break, allowing for flexibility if your docs are part of a greater infrastructure.

**Comment by MaxHillebrand** [comment]
Ok, so no `doc/` at the beginning of the link?
But when in the your repo I try to open [one of the links](https://github.com/thunderBiscuit/WasabiDoc/blob/master/FAQ/FAQ-Introduction.md), I get 404...

**Pull request merged**
