### PR TITLE
add algolia search config

### LINKED ISSUE #38: [FEATURE] Algolia for Activate Content Search
Out-of-the-box, VuePress provides a search box that is looking through only the headers of all the markdown files. As far as I understand, there is an opt-in extension to allow the search for the text in the files.

I think we should activate this, but it might lead to a cluttered search experience.

### PR DESCRIPTION
**Pull request by dennisreimann**
Closes #38.

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
it would be nice to see more search results, for example here, when I first type in `ch` it shows only 3 entries for `change`
screenshot_20191224_095938
and when I then type in `change`, it shows 5.
screenshot_20191224_095947

It might be that there is a limit on 5 search results?

**Comment by MaxHillebrand** [comment]
FYI, the search engine also finds typos and shows results for the fixed word.
For example here I type in `asd`, and it shows results for `and` & `add`.

screenshot_20191224_101019

**Comment by MaxHillebrand** [comment]
And also FYI, the `Search by Algolia` logo is added because wasabi is a free & open source project and thus Algolia graciously provides their tool gratis, though with the caveat of this small advertisement. I think this is very fair.

**Comment by yahiheb** [comment]
Great job guys.

**Comment by yahiheb** [comment]
The problem I see now if you type `HOW DOES WASABI DOWNLOAD A RELEVANT BLOCK?` which is a FAQ you don't see it suggested.

**Comment by MaxHillebrand** [comment]
I also thought that there was an issue with the faq search resultes [#450] but I think everything is working properly, it simply does not say that the result is part of the FAQ, but it is...

screenshot_20191224_161925

**Comment by yahiheb** [comment]
I am not sure I like this. If you type `country` you get many suggestions which have nothing to do with what I am looking for like `contributions` `contributor` `control` ....

**Comment by molnard** [comment]
@dennisreimann that is beautiful, congratulation!

**Pull request merged**
