### PR TITLE
FIX PGP Key step

### PR DESCRIPTION
**Pull request by RiccardoMasutti**
' after zkSNACKs breaks PGP link.

### CODE REVIEW

**Comment by yahiheb** [comment]
The PGP link isn't broken.

**Comment by RiccardoMasutti** [comment]
> The PGP link isn't broken.

brokenlink

**Comment by yahiheb** [comment]
Then you have edited the wrong line. You should edit line number 132 not 105.
I suggest you to simply remove the `'` after `zkSNACKs`.

**Comment by RiccardoMasutti** [comment]
> Then you have edited the wrong line. You should edit line number 132 not 105.
> I suggest you to simply remove the `'` after `zkSNACKs`.

Bot of them were broken. Fixed.

**Comment by yahiheb** [comment]
The first one is not broken for me.
pgp key

**Pull request merged**
