### PR TITLE
Color scheme change

### PR DESCRIPTION
**Pull request by CAnorbo**
Drop blue, get black

### CODE REVIEW

**Review by MaxHillebrand — APPROVED** [review]

**Review by yahiheb — COMMENTED** [review]
What is the motivation for this change?
Is this the only change needed?

I personally prefer the blue with the gradient.

**Comment by yahiheb** [comment]
Master:

Capture1

PR:

Capture

**Comment by yahiheb** [comment]
@CAnorbo @MarnixCroes Should I revert this and only merge when we update our wbsite?

**Comment by CAnorbo** [comment]
> @CAnorbo @MarnixCroes Should I revert this and only merge when we update our website?

No, it's okay. The website will be updated soon.

**Pull request merged**
