### PR TITLE
Add Bitcoin Core variable

### PR DESCRIPTION
**Pull request by RiccardoMasutti**

### CODE REVIEW

**Review by MaxHillebrand — CHANGES_REQUESTED** [review]
we're packaging knots binaries, but support of core binaries too...

though I think, `bitcoinKnotsVersion` is more accurate.

**Comment by yahiheb** [comment]
NACK.
Those version numbers are only used in the tails document as an example so there is no need for a special variable for them, we don't need to maintain this.

**Comment by MaxHillebrand** [comment]
That's a good point @yahiheb.

Then the question is, why do we keep the version numbers in this tails chapter? Can we rewrite the text so that this is not mentioned, thus reducing the maintenance burden further?

**Comment by yahiheb** [comment]
Those are just examples, I think it is ok to keep them as they are IMO.

**Comment by yahiheb** [comment]
@RiccardoMasutti Don't open branches in the repo directly.

**Comment by MaxHillebrand** [comment]
well, if there are the version numbers mentioned, and Core upgrades every 6 months [Knots even more frequent, I think], then I think this justifies a version number so to reduce maintenance efforts in the future.

**Comment by yahiheb** [comment]
We don't need to change those version numbers, they are just examples.

**Review by MaxHillebrand — CHANGES_REQUESTED** [review]
I see @yahiheb, now I understand your rational, and I agree.

NACK 5ba85c4

**Comment by RiccardoMasutti** [comment]
Ok, let's close it

**Pull request closed without merging**
