### PR TITLE
Fix 404 link WhyWasabi

### PR DESCRIPTION
**Pull request by RiccardoMasutti**

### CODE REVIEW

**Comment by RiccardoMasutti** [comment]
https://github.com/zkSNACKs/WasabiDoc/issues/582

**Comment by yahiheb** [comment]
Same as #618

**Comment by yahiheb** [comment]
> Same as #618

@MaxHillebrand this shouldn't have been merged because it is the same in the referenced PR, and that is why you have conflicts in the other one.

**Comment by MaxHillebrand** [comment]
Yes @yahiheb, but #618 is controversial, but this broken link fix is not. So I merged this, because if #618 does not end up getting merged, we still have the fix. 

Not sure if this is the proper way of handling it, as now there needs to be a conflict fix commit...

**Pull request merged**
